PythonInfoSystem/urls.py
from django.contrib import admin
from django.urls import include,  path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('contents/', include('contents.urls'))
]

accounts/urls.py
from django.urls import path
from .views import signup
urlpatterns = [
    path('signup/', signup, name = 'signup')
]

contents/urls.py
from django.urls import path

from . import views

app_name = 'contents'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:topic_id>/', views.topic_detail, name='detail')
]

accounts/models.py
from django.db import models

# Create your models here.

contents/models.py
from django.db import models

class Topic(models.Model):
    topic = models.CharField(max_length=100)
    topic_text = models.TextField()
    def __str__(self):
        return self.topic

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

ACCOUNT_TYPES = [
    ('student', 'Ученик'),
    ('teacher', 'Преподаватель'),
]

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, label='Имя', required=True)
    last_name = forms.CharField(max_length=30, label='Фамилия', required=True)
    email = forms.EmailField(max_length=200, required=True)
    account_type = forms.CharField(label='Выберите тип учётной записи', widget=forms.RadioSelect(choices=ACCOUNT_TYPES))

class meta:
    model = User
    fields = ["first_name", "last_name", "email", "password1", "password2", "account_type"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import SignUpForm

def signup(request):
    form = SignUpForm(request.POST)
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

contents/views.py
from django.shortcuts import get_object_or_404, render
from .models import Topic

def index(request):
    topics_list = Topic.objects.all()
    context = {'topics_list': topics_list}
    return render(request, 'contents/index.html', context)

def topic_detail(request, topic_id):
    topic = get_object_or_404(Topic, pk=topic_id)
    return render(request, 'contents/topic_detail.html', {'topic': topic})

contents/templates/contents/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Информационная система по обучению Python{% endblock %}</title>
</head>

<body>
    <h1>Информационная система по обучению Python</h1>
    {% block content %}
    {% endblock %}
</body>

</html>

contents/templates/contents/index.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <title>Обучение Python</title>
        <meta charset="utf-8">
    </head>
    <body>
        {% if topics_list %}
        <ul>
            {% for topic in topics_list %}
            <li>
                <a href="{% url 'contents:detail' topic.id %}">{{ topic.topic }}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>There are no topics available</p>
        {% endif %}
    </body>
</html>

contents/templates/contents/topic_detail.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <title>{{ topic.topic }}</title>
        <meta charset="utf-8">
    </head>
    <body>
        <h1>{{ topic.topic }}</h1>
        <div>{{ topic.topic_text }}</div>
    </body>
</html>

templates/home.html
{% extends 'contents/base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
{% if user.is_authenticated %}
Добро пожаловать, {{ user.username }}!
<br>
<a href="{% url 'logout' %}">Выйти</a>
{% else %}
<div>
    Добро пожаловать, гость.
    <br>
    Вход не выполнен.
    <br>
    <a href="{% url 'login' %}">Войдите</a>
    <br>
    <a href="{% url 'signup' %}">Зарегистрируйтесь</a>
</div>
{% endif %}
{% endblock %}